name: flagsmith
description: >-
  Flutter Client SDK for https://www.flagsmith.com/, Flagsmith is 100% Open
  Source. Host yourself or let us take care of the hosting.

version: 3.0.3
homepage: https://github.com/Flagsmith/flagsmith-flutter-client
repository: https://github.com/Flagsmith/flagsmith-flutter-client
issue_tracker: https://github.com/Flagsmith/flagsmith-flutter-client/issues

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flagsmith_flutter_core: ^2.3.1
  collection: ^1.15.0
  dio:
    git:
      url: https://github.com/dkrutskikh/dio.git
      ref: develop
      path: dio
  rxdart: ^0.27.5
dev_dependencies:
  test:  ">=1.16.0 <=1.17.12"
  lints: ^1.0.1
  http_mock_adapter: 
    git:
      url: https://github.com/narimanav115/http-mock-adapter.git
      ref: develop
  mockito: ^5.0.15
  test_coverage_badge: ^0.2.0
